feature_select_whitelist:
  - Cells_Count
feature_select_kwargs:
  operation:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
  unique_cut: 0.01
  image_features: True
