cell_count:
  # path to cloned morphmap repo https://github.com/jump-cellpainting/morphmap
  path: /Users/zitong/IP/morphmap/00.0.explore-data/output
  files: crispr_cell_counts.csv.gz
  rename:
    Metadata_Object_Count: Cells_Count
  merge_order: 3
  merge_on:
    - Metadata_Well
    - Metadata_Plate