crispr:
  # path to cloned https://github.com/jump-cellpainting/datasets
  path: /Users/zitong/IP/datasets/metadata
  files: crispr.csv.gz
  filter: "Metadata_Symbol == Metadata_Symbol"
  merge_order: 0
  merge_on:
    - Metadata_JCP2022
