platemap:
  # path to cloned https://github.com/jump-cellpainting/jump-orf-data
  path: /Users/zitong/IP/morphmap_additional/output/platemaps
  files: "*.csv"
  rename:
    plate_name: Metadata_Plate
    plate_map_name: Metadata_plate_map_name
  merge_order: 2
  merge_on:
    - Metadata_Plate
